# Site settings
title: Jagadeesh N Malakannavar
description: 'Software Engineer, Armature Radio Operator, Reiki Healer and Cyclist'
url: 'https;//mnjagadeesh.net'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Jagadeesh N Malakannavar'
  email: mnjagadeesh@gmail.com
  twitter_username: mnjagadeesh
  facebook_username: mnjagadeesh
  github_username:  mnjagadeesh
  linkedin_username:  mnjagadeesh

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
